const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const state = {user:null, departments:[], knowledgeBases:[], folders:[], agents:[], selectedKb:null, selectedFolderId:0, selectedAgent:null, sessionId:null};
const pages = {
  home:["工作台","企业知识与智能体统一入口"], knowledge:["知识库","资料上传、解析、切片与检索索引管理"],
  agents:["智能体","在授权知识范围内获得有出处的回答"], connections:["系统连接","连接 ERP、PLM 与 MOM 等企业业务系统"],
  users:["用户与部门","账号与部门权限管理"], audit:["审计日志","关键操作全程留痕"]
};
const esc = value => String(value ?? "").replace(/[&<>"']/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
const fmt = value => value ? new Date(value).toLocaleString("zh-CN", {hour12:false}) : "—";
const size = bytes => bytes == null ? "—" : bytes < 1024*1024 ? `${(bytes/1024).toFixed(1)} KB` : `${(bytes/1024/1024).toFixed(1)} MB`;
const isAdmin = () => Boolean(state.user?.is_platform_admin);
const canManageKb = (kb=state.selectedKb) => isAdmin() || kb?.permission === "manage";

async function api(path, options={}) {
  const response = await fetch(path, {...options, credentials:"same-origin", headers:{...(options.body instanceof FormData ? {} : {"Content-Type":"application/json"}), ...(options.headers||{})}});
  if (response.status === 401 && !path.includes("/auth/login")) { showLogin(); throw new Error("登录已失效，请重新登录"); }
  const type = response.headers.get("content-type") || "";
  const data = type.includes("json") ? await response.json() : await response.text();
  if (!response.ok) {
    if (response.status >= 500) throw new Error("平台服务暂时不可用，请稍后重试");
    throw new Error(data?.detail || data || `请求失败 (${response.status})`);
  }
  return data;
}
function toast(message, bad=false) { const el=$("#toast"); el.textContent=message; el.className=`toast show${bad?" bad":""}`; clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.className="toast",3000); }
function showLogin(){ $("#app-view").classList.add("hidden"); $("#login-view").classList.remove("hidden"); state.user=null; }
function showApp(){ $("#login-view").classList.add("hidden"); $("#app-view").classList.remove("hidden"); $("#user-name").textContent=state.user.display_name; $("#user-dept").textContent=state.user.departments.map(x=>x.name).join("、")||"未分配部门"; $("#avatar").textContent=state.user.display_name[0]; $$(".admin-only").forEach(el=>el.classList.toggle("hidden",!isAdmin())); navigate("home"); }
function modal(title, html){ $("#modal-title").textContent=title; $("#modal-body").innerHTML=html; $("#modal").showModal(); }
function closeModal(){ $("#modal").close(); }
function badge(status){ const map={succeeded:["已完成","success"],active:["启用","success"],indexed:["已索引","success"],queued:["排队中","pending"],running:["处理中","pending"],processing:["处理中","pending"],pending:["待处理","pending"],failed:["失败","failed"],0:["停用","failed"],1:["启用","success"]}; const item=map[status]||[status||"未知",""]; return `<span class="badge ${item[1]}">${esc(item[0])}</span>`; }

$("#login-form").addEventListener("submit", async event => { event.preventDefault(); const form=new FormData(event.target); $("#login-error").textContent=""; try { const result=await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify(Object.fromEntries(form))}); state.user=result.user; showApp(); } catch(error){ $("#login-error").textContent=error.message; }});
$("#logout").addEventListener("click", async()=>{ try{await api("/api/v1/auth/logout",{method:"POST"});}finally{showLogin();} });
$("#modal-close").addEventListener("click", closeModal);
$("#change-password").addEventListener("click", ()=>{
  modal("修改登录密码",`<form id="change-password-form" class="form-stack"><label>当前密码<input name="current_password" type="password" required></label><label>新密码<input name="new_password" type="password" minlength="10" required></label><p class="muted">至少 10 位，且包含大写、小写、数字和特殊字符。修改后需要重新登录。</p><button class="primary">确认修改</button></form>`);
  $("#change-password-form").onsubmit=async event=>{event.preventDefault();try{await api("/api/v1/auth/change-password",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});closeModal();toast("密码已修改，请重新登录");setTimeout(showLogin,800);}catch(error){toast(error.message,true);}};
});
$("#nav").addEventListener("click", event => { const button=event.target.closest("button[data-page]"); if(button) navigate(button.dataset.page); });

async function navigate(page){
  if ((page==="users"||page==="audit")&&!isAdmin()) return;
  $$("#nav button").forEach(button=>button.classList.toggle("active",button.dataset.page===page));
  $("#page-title").textContent=pages[page][0]; $("#page-subtitle").textContent=pages[page][1]; $("#content").innerHTML='<div class="empty">正在加载…</div>';
  try { await ({home:renderHome,knowledge:renderKnowledge,agents:renderAgents,connections:renderConnections,users:renderUsers,audit:renderAudit}[page])(); }
  catch(error){ $("#content").innerHTML=`<div class="card empty"><strong>加载失败</strong>${esc(error.message)}</div>`; }
}

async function loadBase(){ [state.knowledgeBases,state.agents]=await Promise.all([api("/api/v1/knowledge-bases"),api("/api/v1/agents")]); }
async function renderHome(){
  await loadBase(); let docs=[]; for(const kb of state.knowledgeBases) docs.push(...await api(`/api/v1/documents?knowledge_base_id=${kb.id}&limit=10`));
  const done=docs.filter(x=>x.job_status==="succeeded").length, processing=docs.filter(x=>["queued","running"].includes(x.job_status)).length;
  $("#content").innerHTML=`<div class="stats"><div class="stat"><small>可访问知识库</small><strong>${state.knowledgeBases.length}</strong><span>按部门授权</span></div><div class="stat"><small>知识文档</small><strong>${docs.length}</strong><span>${done} 份已入库</span></div><div class="stat"><small>可用智能体</small><strong>${state.agents.length}</strong><span>权限自动继承</span></div><div class="stat"><small>处理任务</small><strong>${processing}</strong><span>后台异步执行</span></div></div>
  <div class="grid-2"><div class="card"><div class="card-header"><h2>知识处理链路</h2><span class="badge success">完整启用</span></div><div class="pipeline"><div><b>01</b>对象存储</div><div><b>02</b>解析/OCR</div><div><b>03</b>语义切片</div><div><b>04</b>向量索引</div><div><b>05</b>混合检索</div><div><b>06</b>重排序</div></div></div><div class="card"><div class="card-header"><h2>快速开始</h2></div><p class="muted">上传制度资料后，由后台自动完成解析、切片、向量化与全文索引。</p><div class="actions"><button class="primary" onclick="navigate('knowledge')">管理知识库</button><button class="secondary" onclick="navigate('agents')">开始问答</button></div></div></div>`;
}

async function renderKnowledge(selectedId=null){
  const previousKbId=state.selectedKb?.id;
  state.knowledgeBases=await api("/api/v1/knowledge-bases");
  state.selectedKb=state.knowledgeBases.find(x=>x.id===(selectedId||state.selectedKb?.id))||state.knowledgeBases[0]||null;
  if(previousKbId!==state.selectedKb?.id) state.selectedFolderId=0;
  const manage=canManageKb(state.selectedKb), canCreate=isAdmin()||Boolean(state.user?.department_ids?.length);
  $("#content").innerHTML=`<div class="section-head"><div><h2>知识库空间</h2><p>不同部门的数据在服务端强制隔离</p></div>${canCreate?'<button class="primary" id="new-kb">＋ 新建知识库</button>':''}</div><div class="kb-layout"><div class="card"><div class="kb-list">${state.knowledgeBases.map(k=>`<button class="kb-item ${state.selectedKb?.id===k.id?'active':''}" data-kb="${k.id}"><strong>${esc(k.name)}</strong><small>${esc(k.owner_department_name)} · ${k.document_count} 份资料</small></button>`).join("")||'<div class="empty">暂无可访问知识库</div>'}</div></div><div id="kb-detail"></div></div>`;
  $$(".kb-item").forEach(button=>button.onclick=()=>renderKnowledge(Number(button.dataset.kb)));
  if(canCreate) $("#new-kb").onclick=openCreateKb;
  if(state.selectedKb) await renderKbDetail(manage);
}
async function renderKbDetail(manage){
  const kb=state.selectedKb;
  state.folders=await api(`/api/v1/folders?knowledge_base_id=${kb.id}`);
  if(state.selectedFolderId!==0&&!state.folders.some(folder=>folder.id===state.selectedFolderId)) state.selectedFolderId=0;
  const docs=await api(`/api/v1/documents?knowledge_base_id=${kb.id}&folder_id=${state.selectedFolderId}`);
  const selectedFolder=state.folders.find(folder=>folder.id===state.selectedFolderId), locationName=selectedFolder?.path||"根目录";
  const folderTree=`<button class="folder-item ${state.selectedFolderId===0?'active':''}" data-folder="0"><span>⌂</span><strong>根目录</strong></button>${state.folders.map(folder=>`<button class="folder-item ${state.selectedFolderId===folder.id?'active':''}" data-folder="${folder.id}" style="--indent:${8+folder.depth*15}px"><span>▱</span><strong>${esc(folder.name)}</strong><small>${folder.document_count}</small></button>`).join("")}`;
  $("#kb-detail").innerHTML=`<div class="card"><div class="card-header"><div><h2>${esc(kb.name)}</h2><p class="muted">${esc(kb.description||"暂无描述")} · ${esc(kb.code)}</p></div>${manage?`<button class="danger" id="archive-kb">归档知识库</button>`:''}</div><div class="folder-workspace"><aside class="folder-pane"><div class="folder-pane-head"><div><strong>文件夹</strong><small>${state.folders.length} 个目录</small></div>${manage?'<button id="new-folder" class="secondary">＋ 新建</button>':''}</div><div class="folder-tree">${folderTree}</div>${manage&&selectedFolder?`<div class="folder-actions"><button id="edit-folder" class="ghost">重命名/移动</button><button id="delete-folder" class="danger">删除</button></div>`:''}</aside><section class="document-pane"><div class="location-bar"><div><small>当前位置</small><strong>${esc(locationName)}</strong></div><span class="badge">${docs.length} 份资料</span></div>
  ${manage?`<form id="upload-form" class="upload-zone"><label class="upload-field file-field"><span>选择资料文件（支持多选）</span><input type="file" name="files" multiple required></label><label class="upload-field"><span>单文件标题（可选）</span><input name="title" placeholder="多文件上传时自动使用文件名"></label><button class="primary upload-button">上传并入库</button></form>`:''}
  <div class="table-wrap"><table><thead><tr><th>资料</th><th>大小</th><th>处理状态</th><th>切片</th><th>向量</th><th>全文</th><th>更新时间</th><th>操作</th></tr></thead><tbody>${docs.map(d=>`<tr><td><strong>${esc(d.title)}</strong><br><small class="muted">${esc(d.original_filename)}</small></td><td>${size(d.file_size_bytes)}</td><td>${badge(d.job_status||d.extraction_status)}${d.job_error?`<br><small class="error" title="${esc(d.job_error)}">处理失败</small>`:''}</td><td>${d.chunk_count}</td><td>${d.vector_count}/${d.chunk_count}</td><td>${d.fulltext_count}/${d.chunk_count}</td><td>${fmt(d.updated_at)}</td><td><div class="actions"><button class="secondary chunks" data-id="${d.id}">切片</button><button class="ghost download" data-id="${d.id}">下载</button>${manage?`<button class="ghost move-doc" data-id="${d.id}">移动</button><button class="ghost reindex" data-id="${d.id}">重建</button><button class="danger del-doc" data-id="${d.id}">删除</button>`:''}</div></td></tr>`).join("")||'<tr><td colspan="8"><div class="empty">当前文件夹暂无资料</div></td></tr>'}</tbody></table></div></section></div></div>`;
  $$(".folder-item").forEach(button=>button.onclick=async()=>{state.selectedFolderId=Number(button.dataset.folder);await renderKbDetail(canManageKb(kb));});
  if(manage){ $("#upload-form").onsubmit=upload; $("#archive-kb").onclick=archiveKb; $("#new-folder").onclick=()=>openFolderForm(); if(selectedFolder){$("#edit-folder").onclick=()=>openFolderForm(selectedFolder);$("#delete-folder").onclick=()=>deleteFolder(selectedFolder);} }
  $$(".chunks").forEach(x=>x.onclick=()=>showChunks(x.dataset.id)); $$(".download").forEach(x=>x.onclick=()=>location.href=`/api/v1/documents/${x.dataset.id}/download`);
  $$(".move-doc").forEach(x=>x.onclick=()=>moveDocument(docs.find(doc=>doc.id===Number(x.dataset.id))));
  $$(".reindex").forEach(x=>x.onclick=()=>documentAction(x.dataset.id,"reindex")); $$(".del-doc").forEach(x=>x.onclick=()=>documentAction(x.dataset.id,"delete"));
}
function folderOptions(selected=null,exclude=null){return `<option value="">根目录</option>${state.folders.filter(folder=>folder.id!==exclude).map(folder=>`<option value="${folder.id}" ${Number(selected)===folder.id?'selected':''}>${'　'.repeat(folder.depth)}${esc(folder.name)}</option>`).join("")}`;}
function openFolderForm(folder=null){const parentDefault=folder?folder.parent_id:(state.selectedFolderId||null);modal(folder?"编辑文件夹":"新建文件夹",`<form id="folder-form" class="form-stack"><label>文件夹名称<input name="name" value="${esc(folder?.name||'')}" required maxlength="128"></label><label>上级目录<select name="parent_id">${folderOptions(parentDefault,folder?.id)}</select></label><label>排序值<input name="sort_order" type="number" value="${folder?.sort_order||0}"></label><button class="primary">${folder?'保存修改':'创建文件夹'}</button></form>`);$("#folder-form").onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));try{if(folder){await api(`/api/v1/folders/${folder.id}`,{method:"PUT",body:JSON.stringify({name:data.name,parent_id:data.parent_id?Number(data.parent_id):null,sort_order:Number(data.sort_order),row_version:folder.row_version})});}else{await api("/api/v1/folders",{method:"POST",body:JSON.stringify({knowledge_base_id:state.selectedKb.id,name:data.name,parent_id:data.parent_id?Number(data.parent_id):null,sort_order:Number(data.sort_order)})});}closeModal();toast(folder?"文件夹已更新":"文件夹已创建");await renderKbDetail(canManageKb());}catch(error){toast(error.message,true);}};}
async function deleteFolder(folder){if(!confirm(`确定删除空文件夹“${folder.name}”？`))return;try{await api(`/api/v1/folders/${folder.id}?row_version=${folder.row_version}`,{method:"DELETE"});state.selectedFolderId=folder.parent_id||0;toast("文件夹已删除");await renderKbDetail(canManageKb());}catch(error){toast(error.message,true);}}
async function moveDocument(document){modal("移动资料",`<form id="move-document" class="form-stack"><p>将《${esc(document.title)}》移动到：</p><label>目标文件夹<select name="folder_id">${folderOptions(document.folder_id)}</select></label><button class="primary">确认移动</button></form>`);$("#move-document").onsubmit=async event=>{event.preventDefault();const value=new FormData(event.target).get("folder_id");try{await api(`/api/v1/documents/${document.id}/folder`,{method:"PUT",body:JSON.stringify({folder_id:value?Number(value):null,row_version:document.row_version})});closeModal();toast("资料已移动，不需要重新向量化");await renderKbDetail(canManageKb());}catch(error){toast(error.message,true);}};}
async function upload(event){event.preventDefault();const button=event.submitter,files=[...event.target.elements.files.files],title=event.target.elements.title.value.trim();if(!files.length)return;button.disabled=true;try{for(let index=0;index<files.length;index++){button.textContent=`上传中 ${index+1}/${files.length}`;const data=new FormData();data.append("knowledge_base_id",state.selectedKb.id);if(state.selectedFolderId)data.append("folder_id",state.selectedFolderId);if(files.length===1&&title)data.append("title",title);data.append("file",files[index]);await api("/api/v1/documents",{method:"POST",body:data});}toast(`${files.length} 份资料已上传，正在后台建立索引`);await renderKbDetail(canManageKb());}catch(error){toast(error.message,true);}finally{button.disabled=false;button.textContent="上传并入库";}}
async function documentAction(id,action){ if(action==="delete"&&!confirm("确定删除该资料？原文件、切片和检索索引将由后台清理。")) return; try{await api(`/api/v1/documents/${id}${action==="reindex"?"/reindex":""}`,{method:action==="delete"?"DELETE":"POST"});toast(action==="delete"?"删除任务已提交":"重建索引任务已提交");await renderKbDetail(canManageKb());}catch(e){toast(e.message,true);} }
async function showChunks(id){ try{const chunks=await api(`/api/v1/documents/${id}/chunks`);modal("切片与索引状态",`<div class="form-stack">${chunks.map(c=>`<div class="card"><div class="card-header"><strong>切片 ${c.sequence_no}${c.page_start?` · 第 ${c.page_start} 页`:''}</strong><span>${badge(c.vector_status)} ${badge(c.fulltext_status)}</span></div><p>${esc(c.content_text)}</p></div>`).join("")||'<div class="empty">暂无切片</div>'}</div>`);}catch(e){toast(e.message,true);} }
async function archiveKb(){if(!confirm("确定归档整个知识库？其中资料会进入后台删除队列。"))return;try{await api(`/api/v1/knowledge-bases/${state.selectedKb.id}`,{method:"DELETE"});toast("知识库已归档");state.selectedKb=null;await renderKnowledge();}catch(e){toast(e.message,true);} }
async function openCreateKb(){ state.departments=await api("/api/v1/departments"); modal("新建知识库",`<form id="create-kb" class="form-stack"><label>知识库名称<input name="name" required></label><label>唯一编码<input name="code" pattern="[A-Z][A-Z0-9_]+" placeholder="例如 QUALITY_POLICY" required></label><label>所属部门<select name="owner_department_id">${state.departments.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join("")}</select></label><label>密级<select name="security_level"><option value="internal">内部</option><option value="confidential">机密</option><option value="secret">秘密</option><option value="public">公开</option></select></label><label>说明<textarea name="description"></textarea></label><button class="primary">创建知识库</button></form>`); $("#create-kb").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.owner_department_id=Number(data.owner_department_id);try{await api("/api/v1/knowledge-bases",{method:"POST",body:JSON.stringify(data)});closeModal();toast("知识库已创建");await renderKnowledge();}catch(err){toast(err.message,true);}}; }

async function renderAgents(selectedId=null){
  state.agents=await api("/api/v1/agents");
  if(selectedId){
    const agent=state.agents.find(item=>item.id===Number(selectedId));
    if(!agent){toast("该智能体不存在或无权访问",true);return renderAgents();}
    return renderAgentChat(agent);
  }
  state.selectedAgent=null;state.sessionId=null;
  $("#content").innerHTML=`<div class="section-head"><div><h2>可用智能体</h2><p>只展示当前账号有权限使用的智能体，选择后进入独立对话空间</p></div><span class="badge success">${state.agents.length} 个可用</span></div>${state.agents.length?`<div class="agents-grid">${state.agents.map(agent=>`<article class="card agent-list-card"><div class="agent-symbol">✦</div><div class="agent-list-content"><div class="card-header"><div><span class="eyebrow">RAG AGENT</span><h2>${esc(agent.name)}</h2></div>${badge(agent.status)}</div><p>${esc(agent.description||"企业知识问答智能体")}</p><div class="agent-scope"><small>授权知识范围</small><strong>${esc(agent.knowledge_bases||"暂无关联知识库")}</strong></div><button class="primary open-agent" data-id="${agent.id}">进入智能体 <span>→</span></button></div></article>`).join("")}</div>`:`<div class="card empty"><strong>暂无可用智能体</strong>您的部门尚未被授权访问智能体关联的知识库。</div>`}`;
  $$(".open-agent").forEach(button=>button.onclick=()=>renderAgents(Number(button.dataset.id)));
}
async function renderAgentChat(agent){
  state.selectedAgent=agent;state.sessionId=null;
  if(!state.knowledgeBases.length)state.knowledgeBases=await api("/api/v1/knowledge-bases");
  const agentKbIds=String(agent.knowledge_base_ids||"").split(",").filter(Boolean).map(Number),agentKbs=state.knowledgeBases.filter(kb=>agentKbIds.includes(kb.id));
  const folderGroups=await Promise.all(agentKbs.map(async kb=>({kb,folders:await api(`/api/v1/folders?knowledge_base_id=${kb.id}`)})));
  const scopeOptions=`<option value="all">全部授权知识库</option>${folderGroups.map(group=>`<optgroup label="${esc(group.kb.name)}"><option value="${group.kb.id}:all">整个知识库</option><option value="${group.kb.id}:0">仅根目录</option>${group.folders.map(folder=>`<option value="${group.kb.id}:${folder.id}">${'　'.repeat(folder.depth)}${esc(folder.name)}（含子文件夹）</option>`).join("")}</optgroup>`).join("")}`;
  $("#content").innerHTML=`<div class="agent-chat-head"><button id="back-agents" class="secondary">← 返回智能体列表</button><div><h2>${esc(agent.name)}</h2><p>${esc(agent.knowledge_bases)}</p></div></div><div class="chat-layout"><div class="agent-card"><div class="agent-symbol light">✦</div><span class="eyebrow">RAG AGENT</span><h2>${esc(agent.name)}</h2><p>${esc(agent.description)}</p><div class="agent-scope dark"><small>授权知识范围</small><strong>${esc(agent.knowledge_bases)}</strong></div><span class="badge success">已启用</span></div><div class="card chat-box"><label class="chat-scope">本次检索范围<select id="chat-scope-select">${scopeOptions}</select></label><div id="messages" class="messages"><div class="message assistant">您好，我会仅根据您有权访问的企业资料回答，并提供引用来源。您也可以在上方限定知识库或文件夹。</div></div><form id="chat-form" class="chat-input"><textarea name="question" placeholder="请输入您想查询的问题…" required></textarea><button class="primary">发送</button></form></div></div>`;
  $("#back-agents").onclick=()=>renderAgents();
  $("#chat-form").onsubmit=async e=>{e.preventDefault();const input=e.target.question,q=input.value.trim();if(!q)return;appendMessage(q,"user");input.value="";const button=e.submitter;button.disabled=true;const scope=$("#chat-scope-select").value,payload={question:q,session_id:state.sessionId};if(scope!=="all"){const [kbValue,folderValue]=scope.split(":");payload.knowledge_base_id=Number(kbValue);if(folderValue!=="all"){payload.folder_id=Number(folderValue);payload.include_subfolders=true;}}try{const result=await api(`/api/v1/agents/${agent.id}/chat`,{method:"POST",body:JSON.stringify(payload)});state.sessionId=result.session_id;appendMessage(result.answer,"assistant",result.citations,result.retrieval_method);}catch(err){appendMessage(`请求失败：${err.message}`,"assistant");}finally{button.disabled=false;}};
}
function appendMessage(text,role,citations=[],method=null){const box=$("#messages"),el=document.createElement("div");el.className=`message ${role}`;el.textContent=text;if(citations.length){const c=document.createElement("div");c.className="citation";c.innerHTML=`引用：${citations.map(x=>`《${esc(x.title)}》${x.page?`第 ${x.page} 页`:''}`).join("；")}<br>检索：向量 + 关键词 / RRF 融合 / ${method?.rerank==="model"?"模型":"本地"}重排序`;el.append(c);}box.append(el);box.scrollTop=box.scrollHeight;}

async function renderConnections(){const data=await api("/api/v1/connectors");$("#content").innerHTML=`<div class="section-head"><div><h2>企业系统连接</h2><p>连接器当前仅预留架构，不会主动访问生产系统</p></div></div><div class="connector-grid">${data.planned_types.map(x=>`<div class="card connector"><span class="icon">${x.type==='erp'?'▦':x.type==='plm'?'◇':'⌁'}</span><h2>${x.name}</h2><p>${esc(x.description)}</p><span class="coming">待配置接入</span></div>`).join("")}</div><div class="card empty" style="margin-top:18px"><strong>后续接入建议</strong>采用只读服务账号、字段级映射、增量同步、失败重试和完整审计；凭据不存放在普通配置表中。</div>`;}

async function renderUsers(){
  [state.departments,state.users]=await Promise.all([api("/api/v1/departments"),api("/api/v1/users")]);
  $("#content").innerHTML=`<div class="section-head"><div><h2>账号与部门权限</h2><p>权限完全由所属部门决定；平台管理员部门拥有全局管理权限</p></div><div class="actions"><button class="secondary" id="new-dept">＋ 新建部门</button><button class="primary" id="new-user">＋ 创建账号</button></div></div><div class="card"><div class="table-wrap"><table><thead><tr><th>账号</th><th>姓名</th><th>部门</th><th>状态</th><th>最后登录</th><th>操作</th></tr></thead><tbody>${state.users.map(u=>`<tr><td>${esc(u.username)}</td><td>${esc(u.display_name)}</td><td><span class="badge ${u.department_code==='PLATFORM_ADMIN'?'admin-dept':''}">${esc(u.department_name||"未分配")}</span></td><td>${badge(u.status)}</td><td>${fmt(u.last_login_at)}</td><td><div class="actions"><button class="secondary edit-user" data-id="${u.id}">编辑</button><button class="secondary reset-pass" data-id="${u.id}">重置密码</button><button class="${u.status?'danger':'secondary'} user-status" data-id="${u.id}" data-status="${u.status?0:1}">${u.status?'停用':'启用'}</button><button class="danger delete-user" data-id="${u.id}">删除</button></div></td></tr>`).join("")}</tbody></table></div></div>`;
  $("#new-user").onclick=openCreateUser;$("#new-dept").onclick=openCreateDept;
  $$(".user-status").forEach(x=>x.onclick=async()=>{try{await api(`/api/v1/users/${x.dataset.id}/status`,{method:"PATCH",body:JSON.stringify({status:Number(x.dataset.status)})});toast("账号状态已更新");renderUsers();}catch(e){toast(e.message,true);}});
  $$(".edit-user").forEach(x=>x.onclick=()=>openEditUser(Number(x.dataset.id)));
  $$(".reset-pass").forEach(x=>x.onclick=()=>resetPassword(Number(x.dataset.id)));
  $$(".delete-user").forEach(x=>x.onclick=()=>deleteUser(Number(x.dataset.id)));
}
function userForm(user={}){return `<div class="form-grid"><label>用户名<input name="username" value="${esc(user.username||'')}" required></label><label>姓名<input name="display_name" value="${esc(user.display_name||'')}" required></label></div><label>邮箱（可选）<input name="email" type="email" value="${esc(user.email||'')}"></label><label>所属部门<select name="department_id">${state.departments.map(d=>`<option value="${d.id}" ${Number(user.department_id)===d.id?'selected':''}>${esc(d.name)}（${esc(d.code)}）</option>`).join("")}</select></label>`;}
function openCreateUser(){modal("创建企业账号",`<form id="create-user" class="form-stack">${userForm()}<p class="muted">系统会生成安全的临时密码，并且只显示一次。</p><button class="primary">创建账号</button></form>`);$("#create-user").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{const result=await api("/api/v1/users",{method:"POST",body:JSON.stringify({username:d.username,display_name:d.display_name,email:d.email||null,department_id:Number(d.department_id)})});await renderUsers();showTemporaryPassword(result.username,result.temporary_password,"账号创建成功");}catch(err){toast(err.message,true);}};}
function openEditUser(id){const user=state.users.find(item=>item.id===id);if(!user)return;modal("编辑企业账号",`<form id="edit-user" class="form-stack">${userForm(user)}<button class="primary">保存修改</button></form>`);$("#edit-user").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await api(`/api/v1/users/${id}`,{method:"PUT",body:JSON.stringify({username:d.username,display_name:d.display_name,email:d.email||null,department_id:Number(d.department_id)})});closeModal();toast("账号信息已更新");await renderUsers();}catch(err){toast(err.message,true);}};}
function openCreateDept(){modal("新建部门",`<form id="create-dept" class="form-stack"><label>部门名称<input name="name" required></label><label>部门编码<input name="code" pattern="[A-Z][A-Z0-9_]+" placeholder="例如 QUALITY" required></label><button class="primary">创建部门</button></form>`);$("#create-dept").onsubmit=async e=>{e.preventDefault();try{await api("/api/v1/departments",{method:"POST",body:JSON.stringify({...Object.fromEntries(new FormData(e.target)),parent_id:1})});closeModal();toast("部门已创建");renderUsers();}catch(err){toast(err.message,true);}};}
async function resetPassword(id){const user=state.users.find(item=>item.id===id);if(!user||!confirm(`确定重置账号 ${user.username} 的密码？原密码将立即失效。`))return;try{const result=await api(`/api/v1/users/${id}/reset-password`,{method:"POST"});showTemporaryPassword(user.username,result.temporary_password,"密码重置成功");}catch(err){toast(err.message,true);}}
async function deleteUser(id){const user=state.users.find(item=>item.id===id);if(!user||!confirm(`确定删除账号 ${user.username}？该账号将无法登录，审计记录仍会保留。`))return;try{await api(`/api/v1/users/${id}`,{method:"DELETE"});toast("账号已删除");await renderUsers();}catch(err){toast(err.message,true);}}
function showTemporaryPassword(username,password,title){modal(title,`<div class="temporary-password"><p>账号 <strong>${esc(username)}</strong> 的临时密码如下。请立即安全地交给本人，关闭后平台不会再次显示。</p><div class="password-once"><code id="temporary-password-value">${esc(password)}</code><button id="copy-temporary-password" class="secondary" type="button">复制密码</button></div><p class="muted">用户登录后可以在右上角“修改密码”中设置自己的密码。</p><button id="temporary-password-done" class="primary wide" type="button">我已保存，关闭</button></div>`);$("#copy-temporary-password").onclick=async()=>{try{await navigator.clipboard.writeText(password);}catch{const range=document.createRange(),selection=getSelection();range.selectNodeContents($("#temporary-password-value"));selection.removeAllRanges();selection.addRange(range);document.execCommand("copy");selection.removeAllRanges();}toast("临时密码已复制");};$("#temporary-password-done").onclick=closeModal;}
async function renderAudit(){const logs=await api("/api/v1/audit-logs?limit=200");$("#content").innerHTML=`<div class="card"><div class="table-wrap"><table><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>资源</th><th>来源 IP</th></tr></thead><tbody>${logs.map(x=>`<tr><td>${fmt(x.created_at)}</td><td>${esc(x.display_name||x.username||"系统")}</td><td>${esc(x.action)}</td><td>${esc(x.resource_type)} #${esc(x.resource_id||"—")}</td><td>${esc(x.ip_address||"—")}</td></tr>`).join("")||'<tr><td colspan="5"><div class="empty">暂无日志</div></td></tr>'}</tbody></table></div></div>`;}

(async()=>{try{state.user=await api("/api/v1/auth/me");showApp();}catch{showLogin();}})();
