<script setup lang="ts">
import { nextTick, onMounted, ref } from "vue";
import { api } from "../api";
import StatusBadge from "../components/StatusBadge.vue";
const emit=defineEmits<{toast:[message:string,bad?:boolean]}>();
const agents=ref<any[]>([]),kbs=ref<any[]>([]),selected=ref<any>(null),scope=ref("all"),question=ref(""),sessionId=ref<number|null>(null),sending=ref(false),messages=ref<any[]>([]),scopeGroups=ref<any[]>([]);
onMounted(async()=>{agents.value=await api<any[]>("/api/v1/agents");});
async function open(agent:any){selected.value=agent;sessionId.value=null;messages.value=[{role:"assistant",text:"您好，我会仅根据您有权访问的企业资料回答，并提供引用来源。"}];kbs.value=await api<any[]>("/api/v1/knowledge-bases");const ids=String(agent.knowledge_base_ids||"").split(",").filter(Boolean).map(Number);scopeGroups.value=await Promise.all(kbs.value.filter(k=>ids.includes(k.id)).map(async kb=>({kb,folders:await api<any[]>(`/api/v1/folders?knowledge_base_id=${kb.id}`)})));scope.value="all";}
async function send(){const text=question.value.trim();if(!text||sending.value)return;messages.value.push({role:"user",text});question.value="";sending.value=true;const payload:any={question:text,session_id:sessionId.value};if(scope.value!=="all"){const [kb,folder]=scope.value.split(":");payload.knowledge_base_id=Number(kb);if(folder!=="all"){payload.folder_id=Number(folder);payload.include_subfolders=true;}}try{const result=await api<any>(`/api/v1/agents/${selected.value.id}/chat`,{method:"POST",body:JSON.stringify(payload)});sessionId.value=result.session_id;messages.value.push({role:"assistant",text:result.answer,citations:result.citations,method:result.retrieval_method});}catch(e:any){messages.value.push({role:"assistant",text:`请求失败：${e.message}`});emit("toast",e.message,true);}finally{sending.value=false;await nextTick();document.querySelector(".messages")?.scrollTo({top:999999,behavior:"smooth"});}}
</script>
<template>
  <template v-if="!selected"><div class="section-head"><div><h2>可用智能体</h2><p>只展示当前账号有权限使用的智能体</p></div><span class="badge success">{{agents.length}} 个可用</span></div><div v-if="agents.length" class="agents-grid"><article v-for="agent in agents" :key="agent.id" class="card agent-list-card"><div class="agent-symbol">✦</div><div class="agent-list-content"><div class="card-header"><div><span class="eyebrow">RAG AGENT</span><h2>{{agent.name}}</h2></div><StatusBadge :status="agent.status"/></div><p>{{agent.description||"企业知识问答智能体"}}</p><div class="agent-scope"><small>授权知识范围</small><strong>{{agent.knowledge_bases||"暂无关联知识库"}}</strong></div><button class="primary" @click="open(agent)">进入智能体 →</button></div></article></div><div v-else class="card empty">暂无可用智能体</div></template>
  <template v-else><div class="agent-chat-head"><button class="secondary" @click="selected=null">← 返回智能体列表</button><div><h2>{{selected.name}}</h2><p>{{selected.knowledge_bases}}</p></div></div><div class="chat-layout"><div class="agent-card"><div class="agent-symbol light">✦</div><span class="eyebrow">RAG AGENT</span><h2>{{selected.name}}</h2><p>{{selected.description}}</p><div class="agent-scope dark"><small>授权知识范围</small><strong>{{selected.knowledge_bases}}</strong></div><span class="badge success">已启用</span></div><div class="card chat-box"><label class="chat-scope">本次检索范围<select v-model="scope"><option value="all">全部授权知识库</option><optgroup v-for="group in scopeGroups" :key="group.kb.id" :label="group.kb.name"><option :value="group.kb.id+':all'">整个知识库</option><option :value="group.kb.id+':0'">仅根目录</option><option v-for="folder in group.folders" :key="folder.id" :value="group.kb.id+':'+folder.id">{{"　".repeat(folder.depth)}}{{folder.name}}（含子文件夹）</option></optgroup></select></label><div class="messages"><div v-for="(message,index) in messages" :key="index" class="message" :class="message.role">{{message.text}}<div v-if="message.citations?.length" class="citation">引用：<span v-for="(citation,i) in message.citations" :key="i">《{{citation.title}}》{{citation.page?'第 '+citation.page+' 页':''}}{{i<message.citations.length-1?'；':''}}</span><br>检索：向量 + 关键词 / RRF / {{message.method?.rerank==="model"?"模型":"本地"}}重排序</div></div></div><form class="chat-input" @submit.prevent="send"><textarea v-model="question" placeholder="请输入您想查询的问题…" required></textarea><button class="primary" :disabled="sending">{{sending?"回答中…":"发送"}}</button></form></div></div></template>
</template>
