<script setup lang="ts">
import { nextTick, onMounted, ref } from "vue";
import { api } from "../api";
const emit=defineEmits<{toast:[message:string,bad?:boolean]}>();
const agents=ref<any[]>([]),selected=ref<any>(null),question=ref(""),sessionId=ref<string|null>(null),sending=ref(false),messages=ref<any[]>([]);
const modeMeta:Record<string,{label:string,icon:string,hint:string}>={chat:{label:"问答",icon:"✦",hint:"对话查询与知识检索"},form:{label:"任务",icon:"▣",hint:"填写参数后执行任务"},workflow:{label:"流程",icon:"⇢",hint:"多步骤业务流程"},dashboard:{label:"看板",icon:"▥",hint:"业务数据分析看板"},external:{label:"系统",icon:"↗",hint:"打开外部业务应用"}};
const welcomeMessage={role:"assistant",text:"您好，我会仅根据智能体已授权的企业资料回答，并提供引用来源。"};
onMounted(async()=>{agents.value=await api<any[]>("/api/v1/agents");const lastAgentId=Number(sessionStorage.getItem("kb.lastChatAgentId"));const agent=agents.value.find(item=>item.id===lastAgentId&&item.launch_mode==="chat");if(agent)await open(agent);});
async function open(agent:any){selected.value=agent;if(agent.launch_mode!=="chat")return;sessionStorage.setItem("kb.lastChatAgentId",String(agent.id));try{const history=await api<any>(`/api/v1/agents/${agent.id}/chat/latest`);sessionId.value=history.session_id;messages.value=history.messages?.length?history.messages: [welcomeMessage];}catch(e:any){sessionId.value=null;messages.value=[welcomeMessage];emit("toast",e.message,true);}}
function backToList(){sessionStorage.removeItem("kb.lastChatAgentId");selected.value=null;}
async function send(){const text=question.value.trim();if(!text||sending.value)return;messages.value.push({role:"user",text});question.value="";sending.value=true;try{const result=await api<any>(`/api/v1/agents/${selected.value.id}/chat`,{method:"POST",body:JSON.stringify({question:text,session_id:sessionId.value})});sessionId.value=result.session_id;messages.value.push({role:"assistant",text:result.answer,citations:result.citations,method:result.retrieval_method});}catch(e:any){messages.value.push({role:"assistant",text:`请求失败：${e.message}`});emit("toast",e.message,true);}finally{sending.value=false;await nextTick();document.querySelector(".messages")?.scrollTo({top:999999,behavior:"smooth"});}}
</script>
<template>
  <template v-if="!selected"><div class="section-head"><div><h2>可用智能体</h2><p>问答、流程、任务和业务看板统一从这里进入</p></div><span class="badge success">{{agents.length}} 个可用</span></div><div v-if="agents.length" class="agents-grid"><article v-for="agent in agents" :key="agent.id" class="card agent-list-card" @click="open(agent)"><div class="agent-card-top"><div class="agent-symbol compact">{{agent.icon||modeMeta[agent.launch_mode]?.icon||'✦'}}</div><span class="badge">{{modeMeta[agent.launch_mode]?.label||agent.agent_type}}</span></div><div class="agent-list-content"><h2>{{agent.name}}</h2><p>{{agent.description||modeMeta[agent.launch_mode]?.hint}}</p><div class="agent-card-foot"><small>{{agent.category||modeMeta[agent.launch_mode]?.hint}}</small><span>打开 →</span></div></div></article></div><div v-else class="card empty">暂无可用智能体</div></template>
  <template v-else><div class="agent-chat-head"><button class="secondary" @click="backToList">← 返回智能体列表</button><div><h2>{{selected.name}}</h2><p>{{modeMeta[selected.launch_mode]?.hint}}</p></div></div><div v-if="selected.launch_mode==='chat'" class="chat-layout"><div class="agent-card"><div class="agent-symbol light">✦</div><span class="eyebrow">CHAT AGENT</span><h2>{{selected.name}}</h2><p>{{selected.description}}</p><div class="agent-scope dark"><small>授权知识范围</small><strong>{{selected.knowledge_bases}}</strong></div><span class="badge success">已启用</span></div><div class="card chat-box"><div class="chat-scope fixed"><span>检索范围</span><strong>智能体授权知识范围</strong><small>由管理员在智能体配置中统一设定</small></div><div class="messages"><div v-for="(message,index) in messages" :key="index" class="message" :class="message.role">{{message.content||message.text}}<div v-if="message.citations?.length" class="citation">引用：<span v-for="(citation,i) in message.citations" :key="i">《{{citation.title}}》{{citation.page?'第 '+citation.page+' 页':''}}{{i<message.citations.length-1?'；':''}}</span><br>检索：向量 + 关键词 / RRF / {{message.method?.rerank==="model"?"模型":"本地"}}重排序</div></div></div><form class="chat-input" @submit.prevent="send"><textarea v-model="question" placeholder="请输入您想查询的问题…" required></textarea><button class="primary" :disabled="sending">{{sending?"回答中…":"发送"}}</button></form></div></div><div v-else class="card agent-runtime-placeholder"><div class="agent-symbol">{{selected.icon||modeMeta[selected.launch_mode]?.icon}}</div><h2>{{modeMeta[selected.launch_mode]?.label}}型智能体运行区</h2><p>{{selected.description}}</p><div class="runtime-flow"><span>输入业务参数</span><i>→</i><span>调用授权系统与工具</span><i>→</i><span>人工确认关键动作</span><i>→</i><span>输出结果并留痕</span></div><p class="muted">该入口已支持独立运行形态；具体表单、流程步骤和系统工具将在智能体实施时按申请配置。</p></div></template>
</template>
