<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { api } from "../api";
import AppModal from "../components/AppModal.vue";
import StatusBadge from "../components/StatusBadge.vue";
import { formatDate, formatSize } from "../utils";
const props=defineProps<{user:any}>(),emit=defineEmits<{toast:[message:string,bad?:boolean]}>();
const kbs=ref<any[]>([]),folders=ref<any[]>([]),docs=ref<any[]>([]),departments=ref<any[]>([]),selectedKb=ref<any>(null),folderId=ref(0),modal=ref(""),editingFolder=ref<any>(null),movingDoc=ref<any>(null),chunks=ref<any[]>([]),files=ref<File[]>([]),uploading=ref(false);
const form=reactive<any>({name:"",code:"",description:"",owner_department_id:0,security_level:"internal",parent_id:"",sort_order:0,title:"",target_folder_id:""});
const manage=computed(()=>Boolean(props.user?.is_platform_admin)||selectedKb.value?.permission==="manage");
const canCreate=computed(()=>Boolean(props.user?.is_platform_admin)||Boolean(props.user?.department_ids?.length));
const selectedFolder=computed(()=>folders.value.find(x=>x.id===folderId.value));
const location=computed(()=>selectedFolder.value?.path||"根目录");
async function loadKbs(preferred?:number){kbs.value=await api<any[]>("/api/v1/knowledge-bases");selectedKb.value=kbs.value.find(x=>x.id===(preferred||selectedKb.value?.id))||kbs.value[0]||null;if(selectedKb.value)await loadDetail();}
async function loadDetail(){folders.value=await api<any[]>(`/api/v1/folders?knowledge_base_id=${selectedKb.value.id}`);if(folderId.value&&!folders.value.some(x=>x.id===folderId.value))folderId.value=0;docs.value=await api<any[]>(`/api/v1/documents?knowledge_base_id=${selectedKb.value.id}&folder_id=${folderId.value}`);}
onMounted(()=>loadKbs());
async function selectKb(kb:any){selectedKb.value=kb;folderId.value=0;await loadDetail();}
function openKb(){Object.assign(form,{name:"",code:"",description:"",security_level:"internal",owner_department_id:0});api<any[]>("/api/v1/departments").then(data=>{departments.value=data;form.owner_department_id=data[0]?.id||0;modal.value="kb";});}
async function createKb(){try{await api("/api/v1/knowledge-bases",{method:"POST",body:JSON.stringify({...form,owner_department_id:Number(form.owner_department_id)})});modal.value="";await loadKbs();emit("toast","知识库已创建");}catch(e:any){emit("toast",e.message,true);}}
function openFolder(folder?:any){editingFolder.value=folder||null;Object.assign(form,{name:folder?.name||"",parent_id:folder?.parent_id??(folderId.value||""),sort_order:folder?.sort_order||0});modal.value="folder";}
async function saveFolder(){try{if(editingFolder.value)await api(`/api/v1/folders/${editingFolder.value.id}`,{method:"PUT",body:JSON.stringify({name:form.name,parent_id:form.parent_id?Number(form.parent_id):null,sort_order:Number(form.sort_order),row_version:editingFolder.value.row_version})});else await api("/api/v1/folders",{method:"POST",body:JSON.stringify({knowledge_base_id:selectedKb.value.id,name:form.name,parent_id:form.parent_id?Number(form.parent_id):null,sort_order:Number(form.sort_order)})});modal.value="";await loadDetail();emit("toast","文件夹已保存");}catch(e:any){emit("toast",e.message,true);}}
async function deleteFolder(){const f=selectedFolder.value;if(!f||!confirm(`确定删除空文件夹“${f.name}”？`))return;try{await api(`/api/v1/folders/${f.id}?row_version=${f.row_version}`,{method:"DELETE"});folderId.value=f.parent_id||0;await loadDetail();emit("toast","文件夹已删除");}catch(e:any){emit("toast",e.message,true);}}
function onFiles(event:Event){files.value=[...(event.target as HTMLInputElement).files||[]];}
async function upload(){if(!files.value.length)return;uploading.value=true;try{for(const [index,file] of files.value.entries()){const body=new FormData();body.append("knowledge_base_id",String(selectedKb.value.id));if(folderId.value)body.append("folder_id",String(folderId.value));if(files.value.length===1&&form.title)body.append("title",form.title);body.append("file",file);await api("/api/v1/documents",{method:"POST",body});emit("toast",`已上传 ${index+1}/${files.value.length}`);}files.value=[];form.title="";await loadDetail();emit("toast","资料正在后台入库");}catch(e:any){emit("toast",e.message,true);}finally{uploading.value=false;}}
async function action(doc:any,type:"delete"|"reindex"){if(type==="delete"&&!confirm("确定删除该资料？原文件、切片和检索索引将被清理。"))return;try{await api(`/api/v1/documents/${doc.id}${type==="reindex"?"/reindex":""}`,{method:type==="delete"?"DELETE":"POST"});await loadDetail();emit("toast",type==="delete"?"删除任务已提交":"重建索引任务已提交");}catch(e:any){emit("toast",e.message,true);}}
async function showChunks(doc:any){try{chunks.value=await api<any[]>(`/api/v1/documents/${doc.id}/chunks`);modal.value="chunks";}catch(e:any){emit("toast",e.message,true);}}
function openMove(doc:any){movingDoc.value=doc;form.target_folder_id=doc.folder_id||"";modal.value="move";}
async function moveDoc(){try{await api(`/api/v1/documents/${movingDoc.value.id}/folder`,{method:"PUT",body:JSON.stringify({folder_id:form.target_folder_id?Number(form.target_folder_id):null,row_version:movingDoc.value.row_version})});modal.value="";await loadDetail();emit("toast","资料已移动，无需重新向量化");}catch(e:any){emit("toast",e.message,true);}}
async function archive(){if(!confirm("确定归档整个知识库？"))return;try{await api(`/api/v1/knowledge-bases/${selectedKb.value.id}`,{method:"DELETE"});selectedKb.value=null;await loadKbs();emit("toast","知识库已归档");}catch(e:any){emit("toast",e.message,true);}}
</script>
<template>
  <div class="section-head"><div><h2>知识库空间</h2><p>不同部门的数据在服务端强制隔离</p></div><button v-if="canCreate" class="primary" @click="openKb">＋ 新建知识库</button></div>
  <div class="kb-layout"><div class="card"><div class="kb-list"><button v-for="kb in kbs" :key="kb.id" class="kb-item" :class="{active:selectedKb?.id===kb.id}" @click="selectKb(kb)"><strong>{{kb.name}}</strong><small>{{kb.owner_department_name}} · {{kb.document_count}} 份资料</small></button><div v-if="!kbs.length" class="empty">暂无可访问知识库</div></div></div>
  <div v-if="selectedKb" class="card"><div class="card-header"><div><h2>{{selectedKb.name}}</h2><p class="muted">{{selectedKb.description||"暂无描述"}} · {{selectedKb.code}}</p></div><button v-if="manage" class="danger" @click="archive">归档知识库</button></div><div class="folder-workspace"><aside class="folder-pane"><div class="folder-pane-head"><div><strong>文件夹</strong><small>{{folders.length}} 个目录</small></div><button v-if="manage" class="secondary" @click="openFolder()">＋ 新建</button></div><div class="folder-tree"><button class="folder-item" :class="{active:folderId===0}" @click="folderId=0;loadDetail()">⌂ <strong>根目录</strong></button><button v-for="folder in folders" :key="folder.id" class="folder-item" :class="{active:folderId===folder.id}" :style="{'--indent':8+folder.depth*15+'px'}" @click="folderId=folder.id;loadDetail()"><span>▱</span><strong>{{folder.name}}</strong><small>{{folder.document_count}}</small></button></div><div v-if="manage&&selectedFolder" class="folder-actions"><button class="ghost" @click="openFolder(selectedFolder)">重命名/移动</button><button class="danger" @click="deleteFolder">删除</button></div></aside>
  <section class="document-pane"><div class="location-bar"><div><small>当前位置</small><strong>{{location}}</strong></div><span class="badge">{{docs.length}} 份资料</span></div><form v-if="manage" class="upload-zone" @submit.prevent="upload"><label class="upload-field file-field"><span>选择资料文件（支持多选）</span><input type="file" multiple required @change="onFiles"></label><label class="upload-field"><span>单文件标题（可选）</span><input v-model="form.title" placeholder="多文件时使用文件名"></label><button class="primary upload-button" :disabled="uploading">{{uploading?"上传中…":"上传并入库"}}</button></form>
  <div class="table-wrap"><table><thead><tr><th>资料</th><th>大小</th><th>处理状态</th><th>切片</th><th>向量</th><th>全文</th><th>更新时间</th><th>操作</th></tr></thead><tbody><tr v-for="doc in docs" :key="doc.id"><td><strong>{{doc.title}}</strong><br><small class="muted">{{doc.original_filename}}</small></td><td>{{formatSize(doc.file_size_bytes)}}</td><td><StatusBadge :status="doc.job_status||doc.extraction_status"/></td><td>{{doc.chunk_count}}</td><td>{{doc.vector_count}}/{{doc.chunk_count}}</td><td>{{doc.fulltext_count}}/{{doc.chunk_count}}</td><td>{{formatDate(doc.updated_at)}}</td><td><div class="actions"><button class="secondary" @click="showChunks(doc)">切片</button><a class="ghost button-link" :href="'/api/v1/documents/'+doc.id+'/download'">下载</a><template v-if="manage"><button class="ghost" @click="openMove(doc)">移动</button><button class="ghost" @click="action(doc,'reindex')">重建</button><button class="danger" @click="action(doc,'delete')">删除</button></template></div></td></tr><tr v-if="!docs.length"><td colspan="8"><div class="empty">当前文件夹暂无资料</div></td></tr></tbody></table></div></section></div></div></div>
  <AppModal v-if="modal==='kb'" title="新建知识库" @close="modal=''"><form class="form-stack" @submit.prevent="createKb"><label>知识库名称<input v-model="form.name" required></label><label>唯一编码<input v-model="form.code" pattern="[A-Z][A-Z0-9_]+" required></label><label>所属部门<select v-model.number="form.owner_department_id"><option v-for="d in departments" :key="d.id" :value="d.id">{{d.name}}</option></select></label><label>密级<select v-model="form.security_level"><option value="internal">内部</option><option value="confidential">机密</option><option value="secret">秘密</option><option value="public">公开</option></select></label><label>说明<textarea v-model="form.description"></textarea></label><button class="primary">创建知识库</button></form></AppModal>
  <AppModal v-if="modal==='folder'" :title="editingFolder?'编辑文件夹':'新建文件夹'" @close="modal=''"><form class="form-stack" @submit.prevent="saveFolder"><label>名称<input v-model="form.name" required></label><label>上级目录<select v-model="form.parent_id"><option value="">根目录</option><option v-for="f in folders.filter(x=>x.id!==editingFolder?.id)" :key="f.id" :value="f.id">{{"　".repeat(f.depth)}}{{f.name}}</option></select></label><label>排序值<input v-model.number="form.sort_order" type="number"></label><button class="primary">保存</button></form></AppModal>
  <AppModal v-if="modal==='move'" title="移动资料" @close="modal=''"><form class="form-stack" @submit.prevent="moveDoc"><label>目标文件夹<select v-model="form.target_folder_id"><option value="">根目录</option><option v-for="f in folders" :key="f.id" :value="f.id">{{"　".repeat(f.depth)}}{{f.name}}</option></select></label><button class="primary">确认移动</button></form></AppModal>
  <AppModal v-if="modal==='chunks'" title="切片与索引状态" @close="modal=''"><div class="form-stack"><div v-for="chunk in chunks" :key="chunk.id" class="card"><div class="card-header"><strong>切片 {{chunk.sequence_no}}{{chunk.page_start?' · 第 '+chunk.page_start+' 页':''}}</strong><span><StatusBadge :status="chunk.vector_status"/> <StatusBadge :status="chunk.fulltext_status"/></span></div><p>{{chunk.content_text}}</p></div><div v-if="!chunks.length" class="empty">暂无切片</div></div></AppModal>
</template>
