<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { api } from '../api';
const emit = defineEmits<{toast:[message:string,bad?:boolean]}>();
const agents=ref<any[]>([]),departments=ref<any[]>([]),kbs=ref<any[]>([]),models=ref<any[]>([]),tools=ref<any[]>([]);
const tab=ref('config'),editing=ref<number|null>(null),busy=ref(false),revisions=ref<any[]>([]),cases=ref<any[]>([]),runs=ref<any[]>([]),preview=ref<any>(null);
const question=ref(''),labels=ref(''),empty=ref(false);
const form=reactive<any>(defaults());
function defaults(){return {code:'',name:'',description:'',system_prompt:'你是企业业务助手。仅使用授权资料和工具回答，缺少依据时明确说明，不编造企业事实。',launch_mode:'chat',status:'active',llm_gateway_profile_id:null,department_ids:[],knowledge_base_ids:[],tool_ids:[],steps:[],config_version:1,retrieval:{mode:'hybrid',candidate_k:40,top_k:8,rerank_enabled:true,score_threshold:null,context_max_chars:12000,history_messages:12,query_rewrite:true,parent_context:true,max_tool_rounds:3,max_tool_calls:6}}}
function open(a?:any){editing.value=a?.id||null;Object.assign(form,defaults(),a?JSON.parse(JSON.stringify(a)):{});tab.value='config';preview.value=null;revisions.value=[];cases.value=[];runs.value=[];}
async function load(){[agents.value,departments.value,kbs.value,models.value]=await Promise.all([api<any[]>('/api/v1/studio/agents'),api<any[]>('/api/v1/departments'),api<any[]>('/api/v1/knowledge-bases'),api<any[]>('/api/v1/model-gateway/profiles')]);const c=await api<any>('/api/v1/connectors');tools.value=c.items.flatMap((x:any)=>x.tools.map((t:any)=>({...t,label:x.name+' / '+t.tool_name})));}
onMounted(async()=>{await load();open(agents.value[0]);});
async function guard(fn:()=>Promise<void>){busy.value=true;try{await fn();}catch(e:any){emit('toast',e.message,true);}finally{busy.value=false;}}
async function save(){await guard(async()=>{const saved=await api<any>('/api/v1/studio/agents'+(editing.value?'/'+editing.value:''),{method:editing.value?'PUT':'POST',body:JSON.stringify(form)});await load();open(saved);emit('toast','已发布配置版本 v'+saved.config_version);});}
function addStep(){form.steps.push({key:'step_'+(Date.now().toString(36)),type:'retrieve',instruction:'',tool_id:null,arguments:{}});}
function move(i:number,delta:number){const next=i+delta;if(next>=0&&next<form.steps.length){[form.steps[i],form.steps[next]]=[form.steps[next],form.steps[i]];}}
function setArgs(s:any,e:Event){try{s.arguments=JSON.parse((e.target as HTMLTextAreaElement).value);}catch{emit('toast','工具参数需要有效 JSON',true);}}
async function quality(){if(!editing.value)return;await guard(async()=>{tab.value='quality';[cases.value,runs.value]=await Promise.all([api<any[]>(`/api/v1/studio/agents/${editing.value}/cases`),api<any[]>(`/api/v1/studio/agents/${editing.value}/evaluations`)]);});}
async function test(){await guard(async()=>{preview.value=await api(`/api/v1/studio/agents/${editing.value}/test`,{method:'POST',body:JSON.stringify({question:question.value})});});}
async function addCase(){await guard(async()=>{const ids=labels.value.split(/[,，\s]+/).filter(Boolean).map(Number);if(ids.some(x=>!Number.isInteger(x)||x<=0))throw Error('文档 ID 应为正整数');await api(`/api/v1/studio/agents/${editing.value}/cases`,{method:'POST',body:JSON.stringify({question:question.value,expected_document_ids:ids,expect_no_evidence:empty.value})});});await quality();}
async function removeCase(id:number){if(!confirm('删除该评测用例？'))return;await guard(async()=>{await api(`/api/v1/studio/cases/${id}`,{method:'DELETE'});});await quality();}
async function evaluate(){await guard(async()=>{await api(`/api/v1/studio/agents/${editing.value}/evaluations`,{method:'POST'});emit('toast','评测已入队，稍后刷新结果');});await quality();}
async function history(){await guard(async()=>{revisions.value=await api<any[]>(`/api/v1/studio/agents/${editing.value}/revisions`);tab.value='versions';});}
function restore(r:any){const version=form.config_version;Object.assign(form,JSON.parse(JSON.stringify(r.snapshot)),{config_version:version});tab.value='config';emit('toast','历史配置已载入编辑区，点击发布后生效');}
</script>
<template>
 <div class="section-head"><div><h2>智能体工作室</h2><p>配置、编排、检索调试与版本管理</p></div><button class="primary" @click="open()">＋ 新建智能体</button></div>
 <div class="studio-shell">
  <aside class="card studio-list"><button v-for="a in agents" :key="a.id" :class="{active:editing===a.id}" @click="open(a)"><strong>{{a.name}}</strong><small>{{a.launch_mode==='workflow'?'流程':'问答'}} · v{{a.config_version}} · {{a.status}}</small></button></aside>
  <section class="card form-stack"><div class="actions"><button class="secondary" @click="tab='config'">配置与编排</button><button v-if="editing" class="secondary" @click="quality">检索调试 / 评测</button><button v-if="editing" class="secondary" @click="history">历史版本</button></div>
   <form v-if="tab==='config'" class="form-stack" @submit.prevent="save">
    <div class="studio-grid"><label>名称<input v-model="form.name" required></label><label>唯一编码<input v-model="form.code" :disabled="!!editing" required pattern="[A-Z][A-Z0-9_]+"></label><label>运行方式<select v-model="form.launch_mode"><option value="chat">知识与工具问答</option><option value="workflow">步骤式工作流</option></select></label><label>状态<select v-model="form.status"><option value="active">启用</option><option value="disabled">停用</option></select></label></div>
    <label>描述<input v-model="form.description"></label><label>系统提示词<textarea v-model="form.system_prompt" rows="5" required></textarea></label>
    <label>问答模型<select v-model="form.llm_gateway_profile_id"><option :value="null">服务器默认模型</option><option v-for="m in models" :key="m.id" :value="m.id">{{m.name}} / {{m.model_name}}</option></select></label>
    <div class="studio-grid"><fieldset><legend>使用部门（管理员始终可用）</legend><label v-for="d in departments" :key="d.id" class="checkline"><input type="checkbox" v-model="form.department_ids" :value="d.id">{{d.name}}</label></fieldset><fieldset><legend>授权知识库（仍受员工数据权限限制）</legend><label v-for="k in kbs" :key="k.id" class="checkline"><input type="checkbox" v-model="form.knowledge_base_ids" :value="k.id">{{k.name}}</label></fieldset></div>
    <fieldset><legend>可调用只读工具</legend><p class="muted">仅勾选已确认安全的工具；MCP 服务账号也必须配置实际的只读与数据范围权限。</p><label v-for="t in tools.filter(x=>x.annotations?.readOnlyHint===true)" :key="t.id" class="checkline"><input type="checkbox" v-model="form.tool_ids" :value="t.id">{{t.label}}</label></fieldset>
    <details open><summary>检索与上下文策略</summary><div class="studio-grid"><label>检索模式<select v-model="form.retrieval.mode"><option value="hybrid">混合检索 / RRF</option><option value="vector">向量</option><option value="keyword">全文</option></select></label><label>每路候选数<input type="number" v-model.number="form.retrieval.candidate_k" min="5" max="100"></label><label>最终切片数<input type="number" v-model.number="form.retrieval.top_k" min="1" max="20"></label><label>上下文字符预算<input type="number" v-model.number="form.retrieval.context_max_chars" min="2000" max="40000"></label><label>历史消息数<input type="number" v-model.number="form.retrieval.history_messages" min="0" max="30"></label><label>模型分数阈值（留空关闭）<input type="number" :value="form.retrieval.score_threshold??''" @input="form.retrieval.score_threshold=($event.target as HTMLInputElement).value===''?null:Number(($event.target as HTMLInputElement).value)" min="0" max="1" step="0.01"></label></div><label class="checkline"><input type="checkbox" v-model="form.retrieval.rerank_enabled">启用重排序（不可用时降级并记录警告）</label><label class="checkline"><input type="checkbox" v-model="form.retrieval.query_rewrite">对指代追问补充上一问题上下文</label><label class="checkline"><input type="checkbox" v-model="form.retrieval.parent_context">命中子块时扩展父块上下文</label></details>
    <section v-if="form.launch_mode==='workflow'" class="form-stack"><div class="section-head"><h3>工作流步骤</h3><button type="button" class="secondary" @click="addStep">＋ 添加步骤</button></div><p class="muted">顺序执行并保存每步结果。工具参数支持 $input.question、$steps.步骤标识.字段。确认节点暂停，用户确认后继续。暂不支持循环、并行分支和写入业务系统。</p><article class="flow-step" v-for="(s,i) in form.steps" :key="s.key"><div class="actions"><strong>{{i+1}}</strong><input v-model="s.key" aria-label="步骤标识"><select v-model="s.type"><option value="retrieve">知识检索</option><option value="tool">系统工具</option><option value="llm">模型生成</option><option value="approval">人工确认</option></select><button type="button" class="ghost" @click="move(i,-1)">↑</button><button type="button" class="ghost" @click="move(i,1)">↓</button><button type="button" class="danger" @click="form.steps.splice(i,1)">移除</button></div><textarea v-model="s.instruction" placeholder="步骤说明 / 模型生成要求"></textarea><template v-if="s.type==='tool'"><select v-model="s.tool_id"><option :value="null">选择已授权工具</option><option v-for="t in tools.filter(x=>form.tool_ids.includes(x.id))" :key="t.id" :value="t.id">{{t.label}}</option></select><label>参数 JSON<textarea :value="JSON.stringify(s.arguments,null,2)" @change="setArgs(s,$event)" rows="4"></textarea></label></template></article></section>
    <button class="primary" :disabled="busy">{{busy?'保存中…':'发布配置'}}</button>
   </form>
   <section v-else-if="tab==='quality'" class="form-stack"><p class="muted">使用已发布配置，以当前管理员权限检索。评测指标衡量文档召回，不代表回答正确率；部门隔离需另做普通账号验收。</p><label>测试问题<textarea v-model="question" rows="3"></textarea></label><div class="actions"><button class="primary" :disabled="busy||!question" @click="test">检索测试</button><button class="secondary" :disabled="busy||!cases.length" @click="evaluate">运行评测集</button><button class="ghost" @click="quality">刷新结果</button></div><div class="studio-grid"><label>预期文档 ID（逗号分隔）<input v-model="labels" placeholder="从下方检索结果或文档接口获取"></label><label class="checkline"><input type="checkbox" v-model="empty">预期无证据</label></div><button class="secondary" :disabled="busy||!question" @click="addCase">加入评测集</button>
    <section v-if="preview"><p>{{preview.latency_ms}} ms · 重排序 {{preview.rerank}} · 候选 {{JSON.stringify(preview.counts)}}</p><p v-if="preview.warnings.length" class="error">{{preview.warnings.join('，')}}</p><article v-for="u in preview.units" :key="u.id" class="flow-step"><strong>{{u.title}} · 文档 ID {{u.document_id}} / 切片 {{u.id}}</strong><p class="preserve-text">{{u.content_text}}</p></article><p v-if="!preview.units.length">未检索到资料</p></section>
    <h3>评测用例（{{cases.length}}）</h3><div class="table-wrap"><table><tbody><tr v-for="c in cases" :key="c.id"><td>{{c.question}}</td><td>{{c.expect_no_evidence?'无证据':c.expected_document_ids.join(', ')}}</td><td><button class="danger" @click="removeCase(c.id)">删除</button></td></tr></tbody></table></div><h3>评测历史</h3><article v-for="r in runs" :key="r.id" class="flow-step"><strong>{{r.status}} · {{r.created_at}}</strong><p v-if="r.error_code" class="error">{{r.error_code}}</p><div class="metric-grid"><div v-for="(v,k) in r.metrics||{}" :key="k"><small>{{k}}</small><strong>{{v==null?'—':Number(v).toFixed(3)}}</strong></div></div><details><summary>逐题结果与配置快照</summary><pre>{{JSON.stringify({results:r.results,config:r.config},null,2)}}</pre></details></article>
   </section>
   <section v-else class="form-stack"><article v-for="r in revisions" :key="r.version" class="flow-step"><div class="section-head"><strong>版本 {{r.version}} · {{r.created_at}}</strong><button class="secondary" @click="restore(r)">载入此版本</button></div></article><p v-if="!revisions.length">首次通过工作室发布后记录版本。</p></section>
  </section>
 </div>
</template>
